arch_packages:
  - xorg
  - firefox
  - polkit-gnome
  - nitrogen
  - lxappearance
  - thunar
  - xorg-xrandr
  - xorg-server
  - xorg-xinit
  - tmux

arch_fonts:
  - dina-font
  - tamsyn-font
  - ttf-bitstream-vera
  - ttf-croscore
  - ttf-dejavu
  - ttf-droid
  - gnu-free-fonts
  - ttf-ibm-plex
  - ttf-liberation
  - ttf-linux-libertine
  - noto-fonts
  - ttf-roboto
  - tex-gyre-fonts
  - ttf-ubuntu-font-family
  - ttf-anonymous-pro
  - ttf-cascadia-code
  - ttf-fantasque-sans-mono
  - ttf-fira-mono
  - ttf-hack
  - ttf-fira-code
  - ttf-inconsolata
  - ttf-jetbrains-mono
  - ttf-monofur
  - adobe-source-code-pro-fonts
  - cantarell-fonts
  - inter-font
  - ttf-opensans
  - gentium-plus-font
  - ttf-junicode
  - adobe-source-han-sans-otc-fonts
  - adobe-source-han-serif-otc-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji


dwm_suite:
  - dwm
  - dmenu
  - dwmstatus
  - st
  - slock