- name: "Setup ansible user."
  user:
    name: ansible
    system: true

- name: "Add user to sudoers"
  copy:
    src: ../files/ansible_sudoer
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: "Add public ssh key"
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
