- name: "[Archlinux] Install workstations tasks"
  include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"
  tags: archlinux

- name: "Install DWM suite"
  include_tasks: dwm.yml
  tags: dwm

