- name: Setup tmux configuration
  become: true
  become_user: "{{ home_user }}"
  copy:
    src: ~/.tmux.conf
    dest: /home/{{ home_user }}/.tmux.conf

- name: Add tmux folder
  become: true
  become_user: "{{ home_user }}"
  ansible.posix.synchronize:
    src: ~/.tmux/
    dest: /home/{{ home_user }}/.tmux

